apiVersion: v1
kind: Pod
metadata:
  name: mongodb-client
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "internal-app"
    vault.hashicorp.com/agent-inject-secret-mongodb-creds: "internal/data/database/config"
    vault.hashicorp.com/agent-inject-template-mongodb-creds: |
      {{- with secret "internal/data/database/config" -}}
      export MONGO_USER="{{ .Data.data.username }}"
      export MONGO_PASS="{{ .Data.data.password }}"
      {{- end }}
spec:
  serviceAccountName: internal-app
  containers:
  - name: mongo-client
    image: mongo:6.0
    command: ["sleep", "infinity"]