image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017
  nodePort: null

auth:
  rootUser: admin
  rootPassword: mypassword
  enabled: true

persistence:
  enabled: false