apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-login-app
  template:
    metadata:
      labels:
        app: flask-login-app
    spec:
      containers:
      - name: flask-login-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-login-app
spec:
  selector:
    app: flask-login-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000