apiVersion: v1
kind: Pod
metadata:
  name: login-client
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "internal-app"
    vault.hashicorp.com/agent-inject-secret-flask-creds: "internal/data/secrets/config"
    vault.hashicorp.com/agent-inject-template-flask-creds: |
      {{- with secret "internal/data/secrets/config" -}}
      username={{ .Data.data.username }}
      password={{ .Data.data.password }}
      {{- end }}
spec:
  serviceAccountName: internal-app
  containers:
  - name: app
    image: alpine/curl:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Waiting for Vault secrets...";
        while [ ! -f /vault/secrets/flask-creds ]; do sleep 1; done;
        . /vault/secrets/flask-creds;
        echo "Attempting login with username: $username";
        curl -X POST http://flask-login-app:5000/login \
          -H "Content-Type: application/json" \
          -d "{\"username\":\"$username\", \"password\":\"$password\"}";
        sleep 3600